### ISSUE TITLE
ModuleNotFoundError: No module named 'v4_proto'

### ISSUE THREAD

**Issue by A-Jabbar** [dydxprotocol/v4-clients#98]
After installing the Python package via `pip install v4-client-py` and running a basic initialize the client example from the docs:

```
from v4_client_py.clients import CompositeClient
from v4_client_py.clients.constants import Network
client = CompositeClient(
    Network.testnet(),
)
```

I am getting the errors below:
```
Traceback (most recent call last):
  File "d:\work\dydx-v4\execution\utils\dydx_v4_utils.py", line 1, in <module>
    from v4_client_py import IndexerClient
  File "D:\miniconda3\envs\dydx\lib\site-packages\v4_client_py\__init__.py", line 1, in <module>
    from v4_client_py.clients.dydx_indexer_client import IndexerClient
  File "D:\miniconda3\envs\dydx\lib\site-packages\v4_client_py\clients\__init__.py", line 4, in <module>
    from .dydx_validator_client import ValidatorClient
  File "D:\miniconda3\envs\dydx\lib\site-packages\v4_client_py\clients\dydx_validator_client.py", line 4, in <module>
    from .modules.get import Get
  File "D:\miniconda3\envs\dydx\lib\site-packages\v4_client_py\clients\modules\get.py", line 9, in <module>
    from v4_proto.dydxprotocol.clob.order_pb2 import *
ModuleNotFoundError: No module named 'v4_proto'
```

What could be the issue?

**Comment by A-Jabbar** [comment]
Fixed it by installing v4-proto package via `pip install v4-proto`
